<?php
define('BASE_PATH', realpath(__DIR__.'/../').DIRECTORY_SEPARATOR);
define('INC_PATH', BASE_PATH.'inc'.DIRECTORY_SEPARATOR);
define('CLASS_PATH', INC_PATH.'class'.DIRECTORY_SEPARATOR);
define('LANG_PATH', INC_PATH.'lang'.DIRECTORY_SEPARATOR);
define('THEMES_PATH', INC_PATH.'themes'.DIRECTORY_SEPARATOR);